const K=window.KICHOLOCHE_CONFIG||{};const cfg={
"government-updates":{title:"Government Updates",table:"government_updates",select:"title,summary,content,official_link,created_at",date:"created_at",url:"official_link",desc:"Latest verified government information and notices."},
"government-jobs":{title:"Government Jobs",table:"jobs",select:"title,company,location,description,apply_url,status,created_at",date:"created_at",url:"apply_url",desc:"Government and public-sector recruitment information."},
"scholarships":{title:"Scholarships",table:"scholarships",select:"title,tag,published_on,url,created_at",date:"published_on",url:"url",desc:"Scholarship opportunities and education support."},
"results":{title:"Results",table:"results",select:"title,tag,published_on,url,created_at",date:"published_on",url:"url",desc:"Examination and recruitment results."},
"form-fill-up":{title:"Form Fill-up",table:"form_fill_up",select:"title,deadline,apply_link,status,created_at",date:"deadline",url:"apply_link",desc:"Currently running applications and form deadlines."},
"schemes":{title:"Government Schemes",table:"schemes",select:"title,description,eligibility,benefits,official_url,published_at,created_at",date:"published_at",url:"official_url",desc:"Government schemes, benefits and official application information."},
"lottery":{title:"Lottery Results",table:"lottery_results",select:"lottery_name,result_date,result_number,result_text,pdf_url,official_url,created_at",date:"result_date",url:"official_url",desc:"Lottery result information published from configured sources."},
"ai-tools":{title:"AI Tools",table:"ai_tools",select:"name,description,route,active,sort_order,created_at",date:"created_at",url:"route",desc:"Useful browser-based AI tools."},
"quick-links":{title:"Quick Links",table:"quick_links",select:"title,url,sort_order,is_published",date:null,url:"url",desc:"Direct links to important public services."}
};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));const safe=u=>{try{const x=new URL(u,location.href);return["http:","https:","mailto:","tel:"].includes(x.protocol)?x.href:"#"}catch{return"#"}};const fmt=d=>d?new Date(d).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"}):"";
async function load(){const key=document.body.dataset.section,c=cfg[key];document.title=c.title+" — Kicholche";document.querySelector("#title").textContent=c.title;document.querySelector("#desc").textContent=c.desc;try{if(!window.supabase)throw new Error("Database client unavailable");let q=window.supabase.from(c.table).select(c.select).limit(100);if(key==="ai-tools")q=q.order("sort_order",{ascending:true});else if(key==="quick-links")q=q.order("sort_order",{ascending:true});else if(c.date)q=q.order(c.date,{ascending:false});const r=await q;if(r.error)throw r.error;render(r.data||[],c,key)}catch(e){document.querySelector("#grid").innerHTML='<div class="empty">তথ্য লোড করা যায়নি। অনুগ্রহ করে পরে আবার চেষ্টা করুন।</div>'}}
function render(rows,c,key){document.querySelector("#count").textContent=rows.length;const grid=document.querySelector("#grid");if(!rows.length){grid.innerHTML='<div class="empty">এখনও কোনো তথ্য প্রকাশিত হয়নি। Admin Panel থেকে তথ্য প্রকাশ করলে এখানে দেখা যাবে।</div>';return}grid.innerHTML=rows.map(x=>{const title=x.title||x.name||x.lottery_name||"Untitled";const summary=x.summary||x.description||x.result_text||x.benefits||x.company||"";const date=c.date?fmt(x[c.date]):"";const u=safe(x[c.url]||x.pdf_url||"");const button=u!=="#"?(key==="form-fill-up"?"আবেদন করুন":"Official Link"):"";return '<article class="card"><h2>'+esc(title)+'</h2><div class="summary">'+esc(summary)+'</div><div class="meta">'+esc(date)+(x.status?" · "+esc(x.status):"")+(x.location?" · "+esc(x.location):"")+'</div>'+(button?'<div class="actions"><a class="btn" href="'+esc(u)+'" target="_blank" rel="noopener noreferrer">'+button+'</a></div>':"")+'</article>'}).join("")}
function search(){const q=document.querySelector("#filter").value.trim().toLowerCase();document.querySelectorAll(".card").forEach(card=>card.style.display=!q||card.textContent.toLowerCase().includes(q)?"":"none")}
document.addEventListener("DOMContentLoaded",()=>{document.querySelector("#filter").addEventListener("input",search);load()});